sudo: required

language: ruby

rvm:
  - 2.5.1

services:
  - docker

script:
  - bundle exec rake rubocop
  - bundle exec rake

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push suhlig/concourse-github-teams-resource;
    fi
