#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'concourse/github-team-resource/in'
require 'json'

input = JSON.parse(STDIN.read)
script = Concourse::GitHubTeamResource::In.new(ARGV.first)
output = script.call(input['source'], input['version'])
puts JSON.generate(output)
